project:
  type: website

website:
  title: "syntax-styles"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: a11y-light-mod.theme
    code-block-bg: false
    include-before: |-
      <script>
        (function() {
          const sheets = Array.from(document.styleSheets)
            .filter(x => !x.href)

          if (!sheets.length) return;

          // remove the inlined base pandoc syntax styles
          const base_syntax = sheets[0]
          Array.from(base_syntax.cssRules)
            .reduce((res, r, idx) => {
              if (/code span[.][a-z]{2}/.test(r.selectorText)) {
                res = [...res, idx - res.length]
              }
              return(res)
            }, [])
            .forEach(idx_rule => base_syntax.deleteRule(idx_rule))
        })()
      </script>