project:
  type: website

website:
  title: "syntax-styles"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: a11y-light-mod.theme
    code-block-bg: false
